# Generated by Django 5.2.6 on 2025-09-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
