# Generated by Django 5.2.6 on 2025-09-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movierating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieRating',
        ),
    ]
